version: '3.1'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: talks_dev
    env_file: .env
    ports:
      - 8080:3000
    volumes:
      - ./certs:/srv/website/certs:ro
      - ./static:/srv/website/static:ro
      - ./talks.db:/srv/website/talks.db
