services:
  web:
    build: .
    restart: unless-stopped
    container_name: talks
    volumes:
      - ./talks.db:/root/talks.db
      - ./config.toml:/root/config.toml:ro
    expose:
      - 80
    networks:
      - web

networks:
  web:
    external: true
