version: '3.1'

services:
  web:
    build: .
    container_name: talks
    env_file: .env
    ports:
      - 8011:5000
    volumes:
      - ./talks.db:/srv/website/talks.db
    environment:
      VIRTUAL_PORT: 8011
      VIRTUAL_HOST: talks.cosi.clarkson.edu,talks.cslabs.clarkson.edu,talks
      LETSENCRYPT_HOST: talks.cosi.clarkson.edu,talks.cslabs.clarkson.edu

networks:
  default:
    external:
      name: nginx-proxy