version: '3.1'

services:
  web:
    build: .
    restart: always
    container_name: talks
    volumes:
      - ./talks.db:/root/talks.db
      - ./config.toml:/root/config.toml:ro
    ports:
      - 8000:80
